name: deploy
on:
  push:
    branches: [main]
jobs:
  build-windows:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: install-dependencies
        run: yarn install

      - name: run test
        run: yarn test

      - name: build
        run: yarn build
